version: "3"
networks:
  nocobase:
    driver: bridge
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    restart: always
    ports:
      - "${DB_MYSQL_PORT}:3306"
    networks:
      - nocobase
  nocobase:
    # image: node:16-stretch-slim
    build: 
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.dev}
    container_name: nocobase
    networks:
      - nocobase
    working_dir: /app
    env_file: ./.env
    volumes:
      - ./.env:/app/.env
    expose:
      - ${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mysql